CLASSES=\
	org.snakeyaml.engine.v2.serializer.AnchorGenerator	\
	org.snakeyaml.engine.v2.serializer.NumberAnchorGenerator	\
	org.snakeyaml.engine.v2.serializer.Serializer	\
	org.snakeyaml.engine.v2.emitter.EmitterState	\
	org.snakeyaml.engine.v2.emitter.Emitable	\
	org.snakeyaml.engine.v2.emitter.ScalarAnalysis	\
	org.snakeyaml.engine.v2.emitter.Emitter	\
	org.snakeyaml.engine.v2.nodes.Node	\
	org.snakeyaml.engine.v2.nodes.Tag	\
	org.snakeyaml.engine.v2.nodes.ScalarNode	\
	org.snakeyaml.engine.v2.nodes.MappingNode	\
	org.snakeyaml.engine.v2.nodes.AnchorNode	\
	org.snakeyaml.engine.v2.nodes.CollectionNode	\
	org.snakeyaml.engine.v2.nodes.NodeType	\
	org.snakeyaml.engine.v2.nodes.SequenceNode	\
	org.snakeyaml.engine.v2.nodes.NodeTuple	\
	org.snakeyaml.engine.v2.composer.Composer	\
	org.snakeyaml.engine.v2.parser.ParserImpl	\
	org.snakeyaml.engine.v2.parser.Parser	\
	org.snakeyaml.engine.v2.parser.VersionTagsTuple	\
	org.snakeyaml.engine.v2.parser.Production	\
	org.snakeyaml.engine.v2.exceptions.MarkedYamlEngineException	\
	org.snakeyaml.engine.v2.exceptions.YamlEngineException	\
	org.snakeyaml.engine.v2.exceptions.Mark	\
	org.snakeyaml.engine.v2.exceptions.DuplicateKeyException	\
	org.snakeyaml.engine.v2.exceptions.EmitterException	\
	org.snakeyaml.engine.v2.exceptions.MissingEnvironmentVariableException	\
	org.snakeyaml.engine.v2.exceptions.ParserException	\
	org.snakeyaml.engine.v2.exceptions.ConstructorException	\
	org.snakeyaml.engine.v2.exceptions.ScannerException	\
	org.snakeyaml.engine.v2.exceptions.ComposerException	\
	org.snakeyaml.engine.v2.exceptions.ReaderException	\
	org.snakeyaml.engine.v2.exceptions.YamlVersionException	\
	org.snakeyaml.engine.v2.env.EnvConfig	\
	org.snakeyaml.engine.v2.common.ScalarStyle	\
	org.snakeyaml.engine.v2.common.FlowStyle	\
	org.snakeyaml.engine.v2.common.UriEncoder	\
	org.snakeyaml.engine.v2.common.CharConstants	\
	org.snakeyaml.engine.v2.common.NonPrintableStyle	\
	org.snakeyaml.engine.v2.common.SpecVersion	\
	org.snakeyaml.engine.v2.common.ArrayStack	\
	org.snakeyaml.engine.v2.common.Anchor	\
	org.snakeyaml.engine.v2.api.LoadSettingsBuilder	\
	org.snakeyaml.engine.v2.api.DumpSettings	\
	org.snakeyaml.engine.v2.api.Load	\
	org.snakeyaml.engine.v2.api.DumpSettingsBuilder	\
	org.snakeyaml.engine.v2.api.SettingKey	\
	org.snakeyaml.engine.v2.api.LoadSettings	\
	org.snakeyaml.engine.v2.api.ConstructNode	\
	org.snakeyaml.engine.v2.api.YamlUnicodeReader	\
	org.snakeyaml.engine.v2.api.StreamDataWriter	\
	org.snakeyaml.engine.v2.api.lowlevel.Compose	\
	org.snakeyaml.engine.v2.api.lowlevel.Present	\
	org.snakeyaml.engine.v2.api.lowlevel.Parse	\
	org.snakeyaml.engine.v2.api.lowlevel.Serialize	\
	org.snakeyaml.engine.v2.api.RepresentToNode	\
	org.snakeyaml.engine.v2.api.YamlOutputStreamWriter	\
	org.snakeyaml.engine.v2.api.Dump	\
	org.snakeyaml.engine.v2.representer.StandardRepresenter	\
	org.snakeyaml.engine.v2.representer.BaseRepresenter	\
	org.snakeyaml.engine.v2.events.DocumentEndEvent	\
	org.snakeyaml.engine.v2.events.MappingEndEvent	\
	org.snakeyaml.engine.v2.events.ScalarEvent	\
	org.snakeyaml.engine.v2.events.StreamEndEvent	\
	org.snakeyaml.engine.v2.events.CollectionStartEvent	\
	org.snakeyaml.engine.v2.events.NodeEvent	\
	org.snakeyaml.engine.v2.events.StreamStartEvent	\
	org.snakeyaml.engine.v2.events.ImplicitTuple	\
	org.snakeyaml.engine.v2.events.AliasEvent	\
	org.snakeyaml.engine.v2.events.DocumentStartEvent	\
	org.snakeyaml.engine.v2.events.Event	\
	org.snakeyaml.engine.v2.events.SequenceStartEvent	\
	org.snakeyaml.engine.v2.events.SequenceEndEvent	\
	org.snakeyaml.engine.v2.events.CollectionEndEvent	\
	org.snakeyaml.engine.v2.events.MappingStartEvent	\
	org.snakeyaml.engine.v2.scanner.Scanner	\
	org.snakeyaml.engine.v2.scanner.SimpleKey	\
	org.snakeyaml.engine.v2.scanner.StreamReader	\
	org.snakeyaml.engine.v2.scanner.ScannerImpl	\
	org.snakeyaml.engine.v2.tokens.StreamStartToken	\
	org.snakeyaml.engine.v2.tokens.FlowMappingEndToken	\
	org.snakeyaml.engine.v2.tokens.ValueToken	\
	org.snakeyaml.engine.v2.tokens.BlockEntryToken	\
	org.snakeyaml.engine.v2.tokens.AliasToken	\
	org.snakeyaml.engine.v2.tokens.DocumentStartToken	\
	org.snakeyaml.engine.v2.tokens.DirectiveToken	\
	org.snakeyaml.engine.v2.tokens.FlowEntryToken	\
	org.snakeyaml.engine.v2.tokens.DocumentEndToken	\
	org.snakeyaml.engine.v2.tokens.AnchorToken	\
	org.snakeyaml.engine.v2.tokens.FlowSequenceEndToken	\
	org.snakeyaml.engine.v2.tokens.TagToken	\
	org.snakeyaml.engine.v2.tokens.ScalarToken	\
	org.snakeyaml.engine.v2.tokens.BlockMappingStartToken	\
	org.snakeyaml.engine.v2.tokens.StreamEndToken	\
	org.snakeyaml.engine.v2.tokens.BlockSequenceStartToken	\
	org.snakeyaml.engine.v2.tokens.TagTuple	\
	org.snakeyaml.engine.v2.tokens.Token	\
	org.snakeyaml.engine.v2.tokens.FlowMappingStartToken	\
	org.snakeyaml.engine.v2.tokens.FlowSequenceStartToken	\
	org.snakeyaml.engine.v2.tokens.BlockEndToken	\
	org.snakeyaml.engine.v2.tokens.KeyToken	\
	org.snakeyaml.engine.v2.resolver.ResolverTuple	\
	org.snakeyaml.engine.v2.resolver.JsonScalarResolver	\
	org.snakeyaml.engine.v2.resolver.ScalarResolver	\
	org.snakeyaml.engine.v2.constructor.StandardConstructor	\
	org.snakeyaml.engine.v2.constructor.BaseConstructor	\
	org.snakeyaml.engine.external.com.google.gdata.util.common.base.PercentEscaper	\
	org.snakeyaml.engine.external.com.google.gdata.util.common.base.Escaper	\
	org.snakeyaml.engine.external.com.google.gdata.util.common.base.UnicodeEscaper
