CLASSES=\
	org.snakeyaml.engine.utils.SystemPropertyExtension	\
	org.snakeyaml.engine.utils.SystemProperty	\
	org.snakeyaml.engine.v2.emitter.UseUnicodeEncodingTest	\
	org.snakeyaml.engine.v2.emitter.FlexSimleKeyTest	\
	org.snakeyaml.engine.v2.nodes.MappingNodeTest	\
	org.snakeyaml.engine.v2.nodes.NodeTest	\
	org.snakeyaml.engine.v2.composer.ComposerTest	\
	org.snakeyaml.engine.v2.utils.TestUtils	\
	org.snakeyaml.engine.v2.parser.VersionTagsTupleTest	\
	org.snakeyaml.engine.v2.parser.ParserTest	\
	org.snakeyaml.engine.v2.exceptions.MarkTest	\
	org.snakeyaml.engine.v2.common.AnchorTest	\
	org.snakeyaml.engine.v2.common.UriEncoderTest	\
	org.snakeyaml.engine.v2.common.CharConstantsTest	\
	org.snakeyaml.engine.v2.common.SpecVersionTest	\
	org.snakeyaml.engine.v2.api.types.UuidTest	\
	org.snakeyaml.engine.v2.api.types.OptionalTest	\
	org.snakeyaml.engine.v2.api.DumpTest	\
	org.snakeyaml.engine.v2.api.LoadSettingsTest	\
	org.snakeyaml.engine.v2.api.LoadTest	\
	org.snakeyaml.engine.v2.api.LoadMappingTest	\
	org.snakeyaml.engine.v2.api.LoadSequenceTest	\
	org.snakeyaml.engine.v2.api.lowlevel.ParseTest	\
	org.snakeyaml.engine.v2.api.lowlevel.SerializeTest	\
	org.snakeyaml.engine.v2.api.lowlevel.ComposeTest	\
	org.snakeyaml.engine.v2.api.YamlUnicodeReaderTest	\
	org.snakeyaml.engine.v2.api.OptionalMarksTest	\
	org.snakeyaml.engine.v2.api.DumpSettingsTest	\
	org.snakeyaml.engine.v2.api.ConstructNodeTest	\
	org.snakeyaml.engine.v2.representer.EnumRepresenterTest	\
	org.snakeyaml.engine.v2.representer.StandardRepresenterTest	\
	org.snakeyaml.engine.v2.representer.FormatEnum	\
	org.snakeyaml.engine.v2.representer.IndentationTest	\
	org.snakeyaml.engine.v2.events.EventTest	\
	org.snakeyaml.engine.v2.events.ImplicitTupleTest	\
	org.snakeyaml.engine.v2.issues.issue3.ExceptionTest	\
	org.snakeyaml.engine.v2.issues.issue1.NullConstructorTest	\
	org.snakeyaml.engine.v2.scanner.SimpleKeyTest	\
	org.snakeyaml.engine.v2.scanner.ScannerTest	\
	org.snakeyaml.engine.v2.tokens.TokenTest	\
	org.snakeyaml.engine.v2.resolver.JsonScalarResolverTest	\
	org.snakeyaml.engine.v2.resolver.ScalarResolverTupleTest	\
	org.snakeyaml.engine.v2.constructor.StandardConstructorTest	\
	org.snakeyaml.engine.v2.constructor.DefaultConstructorTest	\
	org.snakeyaml.engine.core_schema.NumberTest	\
	org.snakeyaml.engine.issues.issue17.WindowsTest	\
	org.snakeyaml.engine.issues.issue11.TabInFlowContextTest	\
	org.snakeyaml.engine.usecases.references.ReferencesTest	\
	org.snakeyaml.engine.usecases.references.BillionLaughsAttackTest	\
	org.snakeyaml.engine.usecases.references.NonAsciiAnchorTest	\
	org.snakeyaml.engine.usecases.custom_collections.CustomDefaultCollectionsTest	\
	org.snakeyaml.engine.usecases.recursive.RecursiveSetTest	\
	org.snakeyaml.engine.usecases.recursive.RecursiveMapTest	\
	org.snakeyaml.engine.usecases.tags.CustomConstructor	\
	org.snakeyaml.engine.usecases.tags.LocalTagTest	\
	org.snakeyaml.engine.usecases.tags.ImportValueImpl	\
	org.snakeyaml.engine.usecases.tags.TimestampTagTest	\
	org.snakeyaml.engine.usecases.tags.SetsTagTest	\
	org.snakeyaml.engine.usecases.env.CustomEnvConfig	\
	org.snakeyaml.engine.usecases.env.EnvFormatTest	\
	org.snakeyaml.engine.usecases.env.EnvVariableTest	\
	org.snakeyaml.engine.usecases.env.SetEnvVariableTest	\
	org.snakeyaml.engine.usecases.env.EnvTagTest	\
	org.snakeyaml.engine.usecases.binary.BinaryRoundTripTest	\
	org.snakeyaml.engine.usecases.colon_in_flow_context.ColonInFlowContextInListTest	\
	org.snakeyaml.engine.usecases.colon_in_flow_context.ColonInFlowContextInMapTest	\
	org.snakeyaml.engine.usecases.external_test_suite.ParseSuiteTest	\
	org.snakeyaml.engine.usecases.external_test_suite.EmitSuiteTest	\
	org.snakeyaml.engine.usecases.external_test_suite.SuiteUtils	\
	org.snakeyaml.engine.usecases.external_test_suite.SuiteData	\
	org.snakeyaml.engine.usecases.external_test_suite.ComposeSuiteTest	\
	org.snakeyaml.engine.usecases.external_test_suite.EventRepresentationTest	\
	org.snakeyaml.engine.usecases.external_test_suite.EventRepresentation	\
	org.snakeyaml.engine.usecases.inherited.CanonicalParser	\
	org.snakeyaml.engine.usecases.inherited.InheritedMarkTest	\
	org.snakeyaml.engine.usecases.inherited.InheritedReaderTest	\
	org.snakeyaml.engine.usecases.inherited.InheritedCanonicalTest	\
	org.snakeyaml.engine.usecases.inherited.CanonicalException	\
	org.snakeyaml.engine.usecases.inherited.InheritedImportTest	\
	org.snakeyaml.engine.usecases.inherited.InheritedTokensTest	\
	org.snakeyaml.engine.usecases.inherited.CanonicalScanner
